version: '3'

services:
  mysql:
    image: mariadb:10.2.41
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework
  mysql_test:
    image: mariadb:10.2.41
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework_test
