version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker-ci/web/Dockerfile
    working_dir: /app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    volumes:
      - ../frontend:/app/frontend

  mysql:
    container_name: mysql_db
    image: mariadb:10.2.41
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework
  mysql_test:
    container_name: mysql_test_db
    image: mariadb:10.2.41
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework_test
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: docker-ci/backend/Dockerfile
    volumes:
      - ../backend:/app/backend
      - ../config:/app/config
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - mysql_test
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ../:/app/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - web