version: '3'

services:
  mysql:
    container_name: mysql_db
    image: mariadb:10.2.41
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework
  mysql_test:
    container_name: mysql_test_db
    image: mariadb:10.2.41
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=homework_user
      - MYSQL_DATABASE=homework_test
  php:
    container_name: php
    build:
      context: ..
      dockerfile: docker-ci/php-fpm/Dockerfile
    volumes:
      - ../:/app/
    ports:
      - '9000:9000'
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ../:/app/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql